import type { CPTCode } from '../../types/zod/schemas';

export const cptCodes: CPTCode[] = [
  {
    id: 1,
    PK_cptcode: 'CPT_3100F',
    abbreviation: 'FCEXAM',
    type: 'CPT',
    code: '3100F',
    description: 'Fee Carotid Exam',
    options: {},
  },
  {
    id: 2,
    PK_cptcode: 'CPT_49083',
    abbreviation: 'ULTRASOUND GUIDANCE',
    type: 'CPT',
    code: '49083',
    description: 'Ultrasound Guidance',
    options: {},
  },
  {
    id: 3,
    PK_cptcode: 'CPT_51798',
    abbreviation: 'PVR',
    type: 'CPT',
    code: '51798',
    description: 'Pre/Post Void',
    options: {},
  },
  {
    id: 4,
    PK_cptcode: 'CPT_76536',
    abbreviation: 'THYROID',
    type: 'CPT',
    code: '76536',
    description: 'Thyroid',
    options: {},
  },
  {
    id: 5,
    PK_cptcode: 'CPT_76604',
    abbreviation: 'CHEST B SCAN',
    type: 'CPT',
    code: '76604',
    description: 'Chest B Scan',
    options: {},
  },
  {
    id: 6,
    PK_cptcode: 'CPT_76641',
    abbreviation: '',
    type: 'CPT',
    code: '76641',
    description: 'Breast',
    options: {
      type: 'checkbox',
      values: [
        {
          optionId: '76641BIL',
          abbreviation: 'BILAT BREAST',
          label: 'BIL',
        },
        {
          optionId: '76641RT',
          abbreviation: 'RT BREAST',
          label: 'RT',
        },
        {
          optionId: '76641LT',
          abbreviation: 'LT BREAST',
          label: 'LT',
        },
      ],
    },
  },
  {
    id: 7,
    PK_cptcode: 'CPT_76700',
    abbreviation: 'ABD',
    type: 'CPT',
    code: '76700',
    description: 'Abdominal',
    options: {},
  },
  {
    id: 8,
    PK_cptcode: 'CPT_7670A5',
    abbreviation: 'GALLBLADDER',
    type: 'CPT',
    code: '76705',
    description: 'Limited Abdominal - Gallbladder',
    options: {},
  },
  {
    id: 9,
    PK_cptcode: 'CPT_76706',
    abbreviation: 'AAA SCREENING',
    type: 'CPT',
    code: '76706',
    description: 'AAA Screening',
    options: {},
  },
  {
    id: 10,
    PK_cptcode: 'CPT_76770',
    abbreviation: 'RENAL',
    type: 'CPT',
    code: '76770',
    description: 'Renal',
    options: {},
  },
  {
    id: 11,
    PK_cptcode: 'CPT_76805',
    abbreviation: 'OB',
    type: 'CPT',
    code: '76805',
    description: 'Complete OB',
    options: {},
  },
  {
    id: 12,
    PK_cptcode: 'CPT_76810',
    abbreviation: 'OB TWINS',
    type: 'CPT',
    code: '76810',
    description: 'Complete Mult/Gest OB',
    options: {},
  },
  {
    id: 13,
    PK_cptcode: 'CPT_76817',
    abbreviation: 'T.V. OB',
    type: 'CPT',
    code: '76817',
    description: 'OB Transvaginal',
    options: {},
  },
  {
    id: 14,
    PK_cptcode: 'CPT_76830',
    abbreviation: 'T.V.',
    type: 'CPT',
    code: '76830',
    description: 'Transvaginal',
    options: {},
  },
  {
    id: 15,
    PK_cptcode: 'CPT_76856',
    abbreviation: 'PELVIC',
    type: 'CPT',
    code: '76856',
    description: 'Pelvic',
    options: {},
  },
  {
    id: 16,
    PK_cptcode: 'CPT_76857',
    abbreviation: 'BLADDER',
    type: 'CPT',
    code: '76857',
    description: 'Ltd Pelvic (Bladder)',
    options: {},
  },
  {
    id: 17,
    PK_cptcode: 'CPT_76870',
    abbreviation: 'TESTICULAR',
    type: 'CPT',
    code: '76870',
    description: 'Testicular',
    options: {},
  },
  {
    id: 18,
    PK_cptcode: 'CPT_76881',
    abbreviation: 'SOFT TISSUE',
    type: 'CPT',
    code: '76881',
    description: 'Extremity/Soft Tissue non vascular',
    options: {},
  },
  {
    id: 19,
    PK_cptcode: 'CPT_93224',
    abbreviation: 'HOLTER',
    type: 'CPT',
    code: '93224',
    description: '24Hour Hotter Monitor',
    options: {},
  },
  {
    id: 20,
    PK_cptcode: 'CPT_93306',
    abbreviation: 'ECHO',
    type: 'CPT',
    code: '93306',
    description: '2D Echo, Doppler, color flow',
    options: {},
  },
  {
    id: 21,
    PK_cptcode: 'CPT_93880',
    abbreviation: 'CAROTID',
    type: 'CPT',
    code: '93880',
    description: 'Carotid Duplex Bilateral',
    options: {},
  },
  {
    id: 22,
    PK_cptcode: 'CPT_93882',
    abbreviation: '',
    type: 'CPT',
    code: '93882',
    description: 'Carotid Duplex Unilateral',
    options: {
      type: 'checkbox',
      values: [
        {
          optionId: '93882RT',
          abbreviation: 'RT CAROTID',
          label: 'RT',
        },
        {
          optionId: '93882LT',
          abbreviation: 'LT CAROTID',
          label: 'LT',
        },
      ],
    },
  },
  {
    id: 23,
    PK_cptcode: 'CPT_93922',
    abbreviation: 'ABIS',
    type: 'CPT',
    code: '93922',
    description: 'ABI\'s (Ankle/Brachial Indices)',
    options: {},
  },
  {
    id: 24,
    PK_cptcode: 'CPT_93923',
    abbreviation: 'BULSP',
    type: 'CPT',
    code: '93923',
    description: 'Bilateral Upper/Lower Segmental Pressure',
    options: {},
  },
  {
    id: 25,
    PK_cptcode: 'CPT_93925',
    abbreviation: 'BLEA',
    type: 'CPT',
    code: '93925',
    description: 'Bilateral Lower Duplex Extremity Arterial',
    options: {},
  },
  {
    id: 26,
    PK_cptcode: 'CPT_93926',
    abbreviation: '',
    type: 'CPT',
    code: '93926',
    description: 'Unilateral Lower Extremity Arterial',
    options: {
      type: 'checkbox',
      values: [
        {
          optionId: '93926RT',
          abbreviation: 'RLEA',
          label: 'RT',
        },
        {
          optionId: '93926LT',
          abbreviation: 'LLEA',
          label: 'LT',
        },
      ],
    },
  },
  {
    id: 27,
    PK_cptcode: 'CPT_93930',
    abbreviation: 'BUEA',
    type: 'CPT',
    code: '93930',
    description: 'Bilateral Upper Duplex Extremity Arterial',
    options: {},
  },
  {
    id: 28,
    PK_cptcode: 'CPT_93931',
    abbreviation: '',
    type: 'CPT',
    code: '93931',
    description: 'Unilateral Upper Extremity Arterial',
    options: {
      type: 'checkbox',
      values: [
        {
          optionId: '93931RT',
          abbreviation: 'RUEA',
          label: 'RT',
        },
        {
          optionId: '93931LT',
          abbreviation: 'LUEA',
          label: 'LT',
        },
      ],
    },
  },
  {
    id: 29,
    PK_cptcode: 'CPT_93970',
    abbreviation: '',
    type: 'CPT',
    code: '93970',
    description: 'Bilateral Lower Extremity Venous',
    options: {
      type: 'checkbox',
      values: [
        {
          optionId: '93931RT',
          abbreviation: 'BLEV',
          label: '+',
        },
        {
          optionId: '93931LT',
          abbreviation: 'BLEV',
          label: '-',
        },
      ],
    },
  },
  {
    id: 30,
    PK_cptcode: 'CPT_93970A',
    abbreviation: '',
    type: 'CPT',
    code: '93970',
    description: 'Bilateral Upper Extremity Venous',
    options: {
      type: 'checkbox',
      values: [
        {
          optionId: '93970RT',
          abbreviation: 'BUEV',
          label: '+',
        },
        {
          optionId: '93970LT',
          abbreviation: 'BUEV',
          label: '-',
        },
      ],
    },
  },
  {
    id: 31,
    PK_cptcode: 'CPT_93971',
    abbreviation: '',
    type: 'CPT',
    code: '93971',
    description: 'Unilateral Lower Extremity Venous',
    options: {
      type: 'checkbox',
      values: [
        {
          optionId: '93971LRT',
          abbreviation: 'RLEV',
          label: 'RT',
        },
        {
          optionId: '93971LLT',
          abbreviation: 'LLEV',
          label: 'LT',
        },
        {
          optionId: '93971LPLUS',
          abbreviation: '',
          label: '+',
        },
        {
          optionId: '93971LMINUS',
          abbreviation: '',
          label: '-',
        },
      ],
    },
  },
  {
    id: 32,
    PK_cptcode: 'CPT_93971A',
    abbreviation: '',
    type: 'CPT',
    code: '93971',
    description: 'Unilateral Upper Extremity Venous',
    options: {
      type: 'checkbox',
      values: [
        {
          optionId: '93971URT',
          abbreviation: 'RUEV',
          label: 'RT',
        },
        {
          optionId: '93971ULT',
          abbreviation: 'LUEV',
          label: 'LT',
        },
        {
          optionId: '93971UPLUS',
          abbreviation: '',
          label: '+',
        },
        {
          optionId: '93971UMINUS',
          abbreviation: '',
          label: '-',
        },
      ],
    },
  },
  {
    id: 33,
    PK_cptcode: 'CPT_93975',
    abbreviation: 'ABD DOPPLER',
    type: 'CPT',
    code: '93975',
    description: 'Abdominal Doppler',
    options: {},
  },
  {
    id: 34,
    PK_cptcode: 'CPT_93975A',
    abbreviation: 'RENAL DOPPLER',
    type: 'CPT',
    code: '93975',
    description: 'Renal Doppler',
    options: {},
  },
  {
    id: 35,
    PK_cptcode: 'CPT_93978',
    abbreviation: 'AAA',
    type: 'CPT',
    code: '93978',
    description: 'Abdominal Aorta Duplex',
    options: {},
  },
  {
    id: 36,
    PK_cptcode: 'TEXT_Unlist',
    abbreviation: 'COPIES EXAM WRITTEN IN',
    type: 'TEXT',
    code: 'Unlisted',
    description: 'Procedure:',
    value: '',
  },
  {
    id: 38,
    PK_cptcode: 'CPT_76705B',
    abbreviation: 'LIVER',
    type: 'CPT',
    code: '76705',
    description: 'Limited Abdominal - Liver',
    options: {},
  },
  {
    id: 39,
    PK_cptcode: 'CPT_76705C',
    abbreviation: 'PANCREAS',
    type: 'CPT',
    code: '76705',
    description: 'Limited Abdominal - Pancreas',
    options: {},
  },
  {
    id: 39,
    PK_cptcode: 'CPT_76705D',
    abbreviation: 'SPLEEN',
    type: 'CPT',
    code: '76705',
    description: 'Limited Abdominal - Spleen',
    options: {},
  },
  {
    id: 39,
    PK_cptcode: 'CPT_48083',
    abbreviation: 'ULTRASOUND GUIDANCE',
    type: 'CPT',
    code: '48083',
    description: 'Ultrasound Guidance',
    options: {},
  },
  {
    id: 39,
    PK_cptcode: 'CPT_76856A',
    abbreviation: 'PROSTATE',
    type: 'CPT',
    code: '76856',
    description: 'Prostate',
    options: {},
  },
];